server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS