spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
# 映射外部目錄 /data/product-images/ 到 URL 路徑 /images/
  web:
    resources:
      static-locations: file:/Users/yaochilee/static/
mybatis:
  mapper-locations: classpath:mappers/*.xml